services:
  pacs-server:
    image: orthancteam/orthanc:latest
    container_name: pacs-orthanc
    ports:
      - "${ORTHANC_HTTP_PORT:-8042}:8042"
      - "${ORTHANC_DICOM_PORT:-4242}:4242"
    environment:
      ORTHANC__NAME: "${ORTHANC_NAME:-PACS_MAIN}"
      ORTHANC__DICOM_AET: "${ORTHANC_NAME:-PACS_MAIN}"

      DICOM_WEB_PLUGIN_ENABLED: "true"
      ORTHANC__DICOM_WEB__ENABLE: "true"

      DICOM_MODALITIES: |
        {
          "anonymization-server": ["${ANON_ORTHANC_NAME:-PACS_ANON}", "${ANON_ORTHANC_HOST:-host.docker.internal}", ${ANON_ORTHANC_DICOM_PORT:-4243}]
        }

      ORTHANC_EXPLORER_2_PLUGIN_ENABLED: "true"
      ORTHANC__ORTHANC_EXPLORER2__ENABLE: "true"
      ORTHANC__ORTHANC_EXPLORER2__IS_DEFAULT_ORTHANC_UI: "true"
      ORTHANC__AUTHENTICATION_ENABLED: "false"

    volumes:
      - pacs-orthanc:/var/lib/orthanc/db

  pacs-db:
    image: mysql:8.0
    container_name: pacs-db
    ports:
      - "${RDS_PORT:-3306}:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "${RDS_PASS:-pacs_password}"
      MYSQL_DATABASE: "${RDS_NAME:-pacsdb}"
    volumes:
      - pacs-db:/var/lib/mysql

  redis:
    image: redis:latest
    container_name: pacs-redis
    ports:
      - "${REDIS_PORT:-6379}:6379"
    volumes:
      - pacs-redis:/var/lib/redis

volumes:
  pacs-orthanc:
  pacs-db:
  pacs-redis:
