version: '3.8'

services:
  pacs-server:
    image: orthancteam/orthanc:latest # 굳이 full 안 쓰고 기본 latest 써도 충분함!
    container_name: pacs-orthanc
    ports:
      - "8042:8042" # 웹 UI 및 DICOMweb REST API 포트
      - "4242:4242" # DICOM 통신 포트
    environment:
      ORTHANC__NAME: "Hanul_Hospital_PACS"

      # DICOMweb 플러그인 활성화
      DICOM_WEB_PLUGIN_ENABLED: "true"
      ORTHANC__DICOM_WEB__ENABLE: "true"

      # Orthanc Explorer 2 플러그인 활성화
      ORTHANC_EXPLORER_2_PLUGIN_ENABLED: "true"
      ORTHANC__ORTHANC_EXPLORER2__ENABLE: "true"
      ORTHANC__ORTHANC_EXPLORER2__IS_DEFAULT_ORTHANC_UI: "true" # 루트(/) 접속 시 구형 UI 대신 새 UI로 리다이렉트

      # 외부 연동(Next.js / Spring)을 위한 접근 제어
      ORTHANC__AUTHENTICATION_ENABLED: "false"
      ORTHANC__REMOTE_ACCESS_ALLOWED: "true"

    volumes:
      - pacs-orthanc:/var/lib/orthanc/db

  pacs-db:
    image: mysql:8.0
    container_name: pacs-db
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "pacs_password"
      MYSQL_DATABASE: "pacsdb"
    volumes:
      - pacs-db:/var/lib/mysql

  redis:
    image: redis:latest
    container_name: pacs-redis
    ports:
      - "6379:6379"
    volumes:
      - pacs-redis:/var/lib/redis

volumes:
  pacs-orthanc:
  pacs-db:
  pacs-redis: