import type {Metadata} from "next";
import {Geist, Geist_Mono} from "next/font/google";
import "./globals.css";
import Link from "next/link";
import NavUser from "./NavUser";
import Providers from "./Providers";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

/**
 * 애플리케이션의 루트 레이아웃 컴포넌트입니다.
 * 전역 글꼴을 제공하고 컨텍스트 제공자로 애플리케이션을 감쌉니다.
 *
 * @param props - 컴포넌트 속성
 * @param props.children - 레이아웃 내에서 렌더링할 자식 컴포넌트
 * @returns HTML 문서 구조
 */
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="ko"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="bg-canvas text-ink font-sans min-h-full flex flex-col">
        <Providers>
          <header className="flex items-center justify-between border-b border-line bg-paper py-7 px-[clamp(24px,5vw,62px)] max-[560px]:px-5 max-[560px]:py-5 shrink-0">
            <Link href="/" className="font-bold no-underline text-3xl tracking-[-0.01em] text-ink">
              DICOM!
            </Link>
            <NavUser />
          </header>
          {children}
        </Providers>
      </body>
    </html>
  );
}
