import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

import Link from "next/link";
import NavUser from "./nav-user";

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // 임시로 로그인 여부를 저장 (추후 전역 상태나 서버 사이드 인증 정보로 대체 가능)
  const isLogin = true;

  return (
    <html
      lang="ko"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <header className="nav shrink-0">
          <Link href="/" className="logo">
            DICOM!
          </Link>
          {isLogin ? (
            <NavUser />
          ) : (
            <nav className="nav-links">
              <Link href="/#how-it-works">사용방법</Link>
              <Link href="/#faq">FAQ</Link>
            </nav>
          )}
        </header>
        {children}
      </body>
    </html>
  );
}
