services:
  pacs-server-anonymization:
    image: orthancteam/orthanc:latest
    container_name: pacs-orthanc-anonymization
    ports:
      - "${ORTHANC_HTTP_PORT:-8043}:8042"
      - "${ORTHANC_DICOM_PORT:-4243}:4242"
    environment:
      ORTHANC__NAME: "${ORTHANC_NAME:-PACS_ANON}"
      ORTHANC__DICOM_AET: "${ORTHANC_NAME:-PACS_ANON}"

      DICOM_WEB_PLUGIN_ENABLED: "true"
      ORTHANC__DICOM_WEB__ENABLE: "true"

      ORTHANC_EXPLORER_2_PLUGIN_ENABLED: "true"
      ORTHANC__ORTHANC_EXPLORER2__ENABLE: "true"
      ORTHANC__ORTHANC_EXPLORER2__IS_DEFAULT_ORTHANC_UI: "true"
      ORTHANC__AUTHENTICATION_ENABLED: "false"

    volumes:
      - pacs-orthanc-anonymization:/var/lib/orthanc/db

  pacs-db-anonymization:
    image: mysql:8.0
    container_name: pacs-db-anonymization
    ports:
      - "${RDS_PORT:-3307}:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "${RDS_PASS:-anonymization_password}"
      MYSQL_DATABASE: "${RDS_NAME:-anonymizationdb}"
    volumes:
      - pacs-db-anonymization:/var/lib/mysql

  redis-anonymization:
    image: redis:latest
    container_name: pacs-redis-anonymization
    ports:
      - "${REDIS_PORT:-6380}:6379"
    volumes:
      - pacs-redis-anonymization:/data

volumes:
  pacs-orthanc-anonymization:
  pacs-db-anonymization:
  pacs-redis-anonymization:
